### ISSUE TITLE
Cannot use port 80 or 443.

### ISSUE THREAD

**Issue by kierandrewett** [Pikachu920/WebAddon#5]
Hi, if I try and use port 80 so I can hide my port for my domain, the server crashes? Any reason why?

**Comment by kierandrewett** [comment]
Also, how do I send back data like .html and .css?

**Comment by EnderDev** [comment]
`05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! [Skript] Severe Error:
05.10 08:41:03 [Server] ERROR #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! Something went horribly wrong with Skript.
05.10 08:41:03 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
05.10 08:41:03 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
05.10 08:41:03 [Server] ERROR #!#! Following plugins are probably related to this error in some way:
05.10 08:41:03 [Server] ERROR #!#! TuSKe (github.com/Tuke-Nuke/TuSKe)
05.10 08:41:03 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
05.10 08:41:03 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
05.10 08:41:03 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
05.10 08:41:03 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
05.10 08:41:03 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
05.10 08:41:03 [Server] ERROR #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! Stack trace:
05.10 08:41:03 [Server] ERROR #!#! java.lang.NullPointerException
05.10 08:41:03 [Server] ERROR #!#! at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
05.10 08:41:03 [Server] ERROR #!#! at java.lang.Class.forName0(Native Method)
05.10 08:41:03 [Server] ERROR #!#! at java.lang.Class.forName(Class.java:348)
05.10 08:41:03 [Server] ERROR #!#! at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
05.10 08:41:03 [Server] ERROR #!#! at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
05.10 08:41:03 [Server] ERROR #!#! at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
05.10 08:41:03 [Server] ERROR #!#! at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
05.10 08:41:03 [Server] ERROR #!#! at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
05.10 08:41:03 [Server] ERROR #!#! at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
05.10 08:41:03 [Server] ERROR #!#! at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
05.10 08:41:03 [Server] ERROR #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
05.10 08:41:03 [Server] ERROR #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
05.10 08:41:03 [Server] ERROR #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
05.10 08:41:03 [Server] ERROR #!#! at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
05.10 08:41:03 [Server] ERROR #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
05.10 08:41:03 [Server] ERROR #!#! at java.lang.Thread.run(Thread.java:748)
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! Version Information:
05.10 08:41:03 [Server] ERROR #!#! Skript: 2.2-dev36
05.10 08:41:03 [Server] ERROR #!#! Bukkit: 1.11.2-R0.1-SNAPSHOT
05.10 08:41:03 [Server] ERROR #!#! Minecraft: 1.11.2
05.10 08:41:03 [Server] ERROR #!#! Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
05.10 08:41:03 [Server] ERROR #!#! OS: Linux amd64 4.14.12-xxxx-std-ipv6-64
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! Server platform: Spigot
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! Current node: null
05.10 08:41:03 [Server] ERROR #!#! Current item: null
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! Thread: Server thread
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! Language: english
05.10 08:41:03 [Server] ERROR #!#! Link parse mode: DISABLED
05.10 08:41:03 [Server] ERROR #!#!
05.10 08:41:03 [Server] ERROR #!#! End of Error.
05.10 08:41:03 [Server] ERROR #!#!`

**Comment by Olyno** [comment]
> Hi, if I try and use port 80 so I can hide my port for my domain, the server crashes? Any reason why?

Work fine for me. Check if you have webaddon 1.1. You can't check with "/ver webaddon" because he didn't update the version in this command.

> Also, how do I send back data like .html and .css?

Use:
```vb
send back file contents of "your file.html"
```
You can't import a css from an external file yet, doesn't work correctly.

**Comment by kierandrewett** [comment]
Yeah, I'm using 1.1, Should I use 1.0? http://i-hate.ender.site/i/9KIDQ5.png

I'll try send back file contents.

**Comment by kierandrewett** [comment]
well that didn't work. https://hastebin.com/tozuxayege.apache

Also this is my web-addon file: https://hastebin.com/satedehaco.coffeescript
